/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as PodcastRouteImport } from './routes/podcast'
import { Route as NewsletterRouteImport } from './routes/newsletter'
import { Route as MeditationsRouteImport } from './routes/meditations'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as ChaptersRouteImport } from './routes/chapters'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsProductIdRouteImport } from './routes/products/$productId'

const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const PodcastRoute = PodcastRouteImport.update({
  id: '/podcast',
  path: '/podcast',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsletterRoute = NewsletterRouteImport.update({
  id: '/newsletter',
  path: '/newsletter',
  getParentRoute: () => rootRouteImport,
} as any)
const MeditationsRoute = MeditationsRouteImport.update({
  id: '/meditations',
  path: '/meditations',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const ChaptersRoute = ChaptersRouteImport.update({
  id: '/chapters',
  path: '/chapters',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsProductIdRoute = ProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/chapters': typeof ChaptersRoute
  '/community': typeof CommunityRoute
  '/meditations': typeof MeditationsRoute
  '/newsletter': typeof NewsletterRoute
  '/podcast': typeof PodcastRoute
  '/resources': typeof ResourcesRoute
  '/shop': typeof ShopRoute
  '/tools': typeof ToolsRoute
  '/products/$productId': typeof ProductsProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/chapters': typeof ChaptersRoute
  '/community': typeof CommunityRoute
  '/meditations': typeof MeditationsRoute
  '/newsletter': typeof NewsletterRoute
  '/podcast': typeof PodcastRoute
  '/resources': typeof ResourcesRoute
  '/shop': typeof ShopRoute
  '/tools': typeof ToolsRoute
  '/products/$productId': typeof ProductsProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/chapters': typeof ChaptersRoute
  '/community': typeof CommunityRoute
  '/meditations': typeof MeditationsRoute
  '/newsletter': typeof NewsletterRoute
  '/podcast': typeof PodcastRoute
  '/resources': typeof ResourcesRoute
  '/shop': typeof ShopRoute
  '/tools': typeof ToolsRoute
  '/products/$productId': typeof ProductsProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/chapters'
    | '/community'
    | '/meditations'
    | '/newsletter'
    | '/podcast'
    | '/resources'
    | '/shop'
    | '/tools'
    | '/products/$productId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/chapters'
    | '/community'
    | '/meditations'
    | '/newsletter'
    | '/podcast'
    | '/resources'
    | '/shop'
    | '/tools'
    | '/products/$productId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/chapters'
    | '/community'
    | '/meditations'
    | '/newsletter'
    | '/podcast'
    | '/resources'
    | '/shop'
    | '/tools'
    | '/products/$productId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRoute
  ChaptersRoute: typeof ChaptersRoute
  CommunityRoute: typeof CommunityRoute
  MeditationsRoute: typeof MeditationsRoute
  NewsletterRoute: typeof NewsletterRoute
  PodcastRoute: typeof PodcastRoute
  ResourcesRoute: typeof ResourcesRoute
  ShopRoute: typeof ShopRoute
  ToolsRoute: typeof ToolsRoute
  ProductsProductIdRoute: typeof ProductsProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/podcast': {
      id: '/podcast'
      path: '/podcast'
      fullPath: '/podcast'
      preLoaderRoute: typeof PodcastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsletter': {
      id: '/newsletter'
      path: '/newsletter'
      fullPath: '/newsletter'
      preLoaderRoute: typeof NewsletterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meditations': {
      id: '/meditations'
      path: '/meditations'
      fullPath: '/meditations'
      preLoaderRoute: typeof MeditationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters': {
      id: '/chapters'
      path: '/chapters'
      fullPath: '/chapters'
      preLoaderRoute: typeof ChaptersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$productId': {
      id: '/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof ProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRoute,
  ChaptersRoute: ChaptersRoute,
  CommunityRoute: CommunityRoute,
  MeditationsRoute: MeditationsRoute,
  NewsletterRoute: NewsletterRoute,
  PodcastRoute: PodcastRoute,
  ResourcesRoute: ResourcesRoute,
  ShopRoute: ShopRoute,
  ToolsRoute: ToolsRoute,
  ProductsProductIdRoute: ProductsProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
